# Generated by Django 5.1.3 on 2026-07-16 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_url', models.URLField()),
                ('recipe_image', models.URLField(blank=True, null=True)),
                ('recipe_description', models.TextField(blank=True, null=True)),
                ('element_name', models.CharField(max_length=200)),
                ('element_type', models.CharField(max_length=50)),
                ('allergens', models.JSONField(default=list)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='recipe', max_length=50)),
                ('element', models.CharField(max_length=200)),
                ('allergens', models.JSONField(default=list)),
                ('num_recipes', models.IntegerField(default=0)),
                ('num_recipes_with_allergen', models.IntegerField(default=0)),
                ('recipe_urls', models.JSONField(default=list)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
