# Generated by Django 5.1.3 on 2026-07-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='element',
            field=models.CharField(max_length=1000),
        ),
    ]
