# Generated by Django 5.1.3 on 2026-08-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_savedsearch_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='percent_safe_recipes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='unsafe_recipes',
            field=models.JSONField(default=list),
        ),
    ]
