# Generated by Django 5.1.3 on 2025-08-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedsearch',
            old_name='dish',
            new_name='element',
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='type',
            field=models.CharField(default='recipe', max_length=50),
        ),
    ]
