# Generated by Django 5.1.3 on 2025-08-17 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_dish_savedsearch_element_savedsearch_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_url', models.URLField()),
                ('recipe_image', models.URLField(blank=True, null=True)),
                ('recipe_description', models.TextField(blank=True, null=True)),
                ('element_name', models.CharField(max_length=200)),
                ('element_type', models.CharField(max_length=50)),
                ('allergens', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
