# Generated by Django 5.1.3 on 2026-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
